### ISSUE TITLE
Please verify (and fix) implementations using Reactive Streams TCK

### ISSUE THREAD

**Issue by ktoso** [pwittchen/java-flow-experiments#1]
Hi there,
codifying my request to please check the implementations using the technology compatibility kit ( 
https://github.com/reactive-streams/reactive-streams-jvm/tree/master/tck ) before showing them to people.

It's very important that we do not show people incorrect implementations of these interfaces (as the ones in `Main.java`) as it will hurt the entire Flow.* / Reactive Streams ecosystem if there will be incorrect implementations floating around.

Thanks for your understanding and please feel free to reach out on https://github.com/reactive-streams/reactive-streams-jvm if you're unsure about some part of the specification. Thanks!

**Comment by pwittchen** [comment]
Thanks for reporting this issue. I'll check it using TCK and update code if
necessary. In the case of questions, I'll ask them in this issue.

10.10.2017 3:17 AM "ktoso" <notifications@github.com> napisał(a):

**Comment by pwittchen** [comment]
I've started migrating Java9 project to Gradle in PR #2 and added appropriate test dependencies inlcuding TCK. Later, I'm going to add compatibility tests using TCK.

**Comment by pwittchen** [comment]
Hi @ktoso,

I tried to add TCK tests extending `PublisherVerification`, `SubscriberBlackboxVerification` and `SubscriberWhiteboxVerification`. I'm not sure if I understand all of that correctly, but I see many failing generic tests and there's a lot of effort to make simple "hello world" RS example compatible with TCK. I think, I'm not competent enough to make complete production-ready RS implementation passing TCK tests only by myself for now in a short period of time. Can you give me some hints or examples?

If there's as much work and knowledge required for the simplest example as I think, I'll just delete this example with custom RS implementation, remove code snippet from presentation slides and add info about TCK to not confuse people.

What do you think?

**EDIT**

I've read your comment on my blog once again and took a look at this example https://github.com/reactive-streams/reactive-streams-jvm/tree/master/examples/src/main/java/org/reactivestreams/example/unicast. Maybe for now I'll just use this example here and remove invalid example, which does not pass TCK tests.

**Comment by pwittchen** [comment]
Ok, I've updated basic example in PR #3 with the one, which passes TCK tests. This example is copied from examples in Reactive Streams repository (I've kept license information in the files). I've also removed wrong implementations from my slides at https://speakerdeck.com/pwittchen/get-ready-for-java-dot-util-dot-concurrent-dot-flow and left only empty interfaces, so it shouldn't be confusing now. Moreover, I mentioned TCK in the slides.

I hope, this is fine now and currently provided examples are correct.

Please take a look on that and let me know if it's OK or if I should improve something else.

**Comment by ktoso** [comment]
> there's a lot of effort to make simple "hello world" RS example compatible with TCK. 

That's exactly the point I've wanted to get across – it's a very difficult thing to implement correctly, thus showing people "hey, let's implement it" is harmful, since then we'd have wrong implementations floating around and people complaining that "Flow does not work" :)

> I'll just delete this example with custom RS implementation, remove code snippet from presentation slides and add info about TCK to not confuse people.

Yes, I think that's fine; or you could show the example from the RS repository or sources of the :)

Thanks a ton for updating the published presentation!
Indeed the examples at https://github.com/reactive-streams/reactive-streams-jvm/blob/master/examples/src/main/java/org/reactivestreams/example/unicast/AsyncSubscriber.java and https://github.com/reactive-streams/reactive-streams-jvm/blob/master/examples/src/main/java/org/reactivestreams/example/unicast/AsyncIterablePublisher.java are the "reference examples", and they also show that implementing these is non-trivial.

I would also propose to add spec and tck links in the README here, which I can submit a PR for if you want.

Thanks again

**Comment by pwittchen** [comment]
I've already merged mentioned PR. I think, this issue is clarified now and we can close it. :)

Thanks a lot for your constructive feedback!

**Comment by ktoso** [comment]
Thanks a lot for being so responsive and handling the feedback so well :)
If only everyone in the open source ecosystem would be so nice to work with, thanks!
